Repository Ya-dola/spark-web, pull requests merged in 2024-10, with the labels that each got.

#93 Create nextjs.yml
  .github/workflows/nextjs.yml
Labels: enhancement, feature

#96 fix(pages): fix mobile view
  clients/challenge/challenge_client.tsx
  clients/pi_community/pi_community_client.tsx
  clients/spark_home/spark_home_client.tsx
  clients/undergraduate/undergraduate_client.tsx
  components/community_section/community_section.tsx
  components/image_grid/image_grid.tsx
  components/scrollable_segmented_control/scrollable_segmented_control.tsx
  components/transitions_component/transitions.tsx
  constants/community/pi_mora.json
  constants/community/tech_demo.json
Labels: bug, enhancement

#100 feat(carousel-tab): add new carousel layout
  clients/pi_community/pi_community_client.tsx
  clients/spark_home/spark_home_client.tsx
  components/carousel_tab/carousel_tab.tsx
  components/community_section/community_section.tsx
  components/transitions_component/transitions.tsx
Labels: feature

#104 fix(carousel-tab): fix mobile view for carousel tab
  components/carousel_tab/carousel_tab.tsx
Labels: enhancement

#105 fix(carousel-tab): fix carousel controls
  clients/pi_community/pi_community_client.tsx
  components/carousel_tab/carousel_tab.module.css
  components/carousel_tab/carousel_tab.tsx
  components/community_section/community_section.tsx
Labels: enhancement

#106 fix(challenge-client): add new carousel to challenge
  clients/challenge/challenge_client.tsx
  clients/undergraduate/undergraduate_client.tsx
Labels: enhancement

#108 fix(challenge-client): fix mobile bg
  clients/challenge/challenge_client.tsx
  components/carousel_tab/carousel_tab.tsx
  components/custom_app_shell/custom_app_shell.tsx
Labels: bug, feature

#110 fix(carousel-tab): fix character limit
  clients/challenge/challenge_client.tsx
  components/carousel_tab/carousel_tab.tsx
  constants/challenge/challenge.json
Labels: enhancement, refactor

#124 fix(carousel-tab): fix border radius
  clients/challenge/challenge_client.tsx
  components/carousel_tab/carousel_tab.tsx
Labels: bug

#127 Issue 126 - add image modal viewer to carousel tab
  components/carousel_tab/carousel_tab.tsx
  components/image_modal/image_modal.tsx
Labels: feature

#130 refactor(constants): add json docs and images
  components/carousel_tab/carousel_tab.tsx
  constants/challenge/challenge.json
  constants/community/final_year.json
  constants/community/pi_mora.json
  constants/community/tech_demo.json
  public/images/maintainedData/challenge/1st_runner_up_21_22.jpg
  public/images/maintainedData/challenge/1st_runner_up_21_22_device.png
  public/images/maintainedData/challenge/1st_runner_up_22_23.jpeg
  public/images/maintainedData/challenge/1st_runner_up_22_23_device.jpg
  public/images/maintainedData/challenge/1st_runner_up_23_24.jpeg
  public/images/maintainedData/challenge/2nd_runner_up_21_22.jpg
  public/images/maintainedData/challenge/2nd_runner_up_21_22_device.png
  public/images/maintainedData/challenge/2nd_runner_up_22_23.jpeg
  public/images/maintainedData/challenge/2nd_runner_up_22_23_device.jpeg
  public/images/maintainedData/challenge/2nd_runner_up_23_24.jpeg
  public/images/maintainedData/challenge/winner_21_22.jpg
  public/images/maintainedData/challenge/winner_21_22_device.png
  public/images/maintainedData/challenge/winner_22_23.jpeg
  public/images/maintainedData/challenge/winner_23_24.jpeg
  public/images/maintainedData/finalYear/18th_batch_fyp_1_img_1.jpg
  public/images/maintainedData/finalYear/18th_batch_fyp_1_img_2.jpg
  public/images/maintainedData/finalYear/18th_batch_fyp_2_img_1.png
  public/images/maintainedData/finalYear/18th_batch_fyp_2_img_2.png
  public/images/maintainedData/finalYear/19th_batch_fyp_1.jpg
  public/images/maintainedData/piMora/PiMORA1_img1.jpeg
  public/images/maintainedData/piMora/PiMORA1_img2.jpeg
  public/images/maintainedData/piMora/PiMORA2_img1.jpeg
  public/images/maintainedData/techDemo/Group1.jpg
  public/images/maintainedData/techDemo/Group1_1.png
  public/images/maintainedData/techDemo/Team_Fusion_01.png
  public/images/maintainedData/techDemo/Team_Fusion_02.png
  public/images/maintainedData/techDemo/Team_Fusion_03.png
  public/images/maintainedData/techDemo/cultiwave.jpeg
  public/images/maintainedData/techDemo/cultiwave_1.jpg
  public/images/maintainedData/techDemo/cultiwave_2.jpg
  public/images/maintainedData/techDemo/cultiwave_3.jpg
  public/images/maintainedData/techDemo/cultiwave_4.jpg
  public/images/maintainedData/techDemo/group2_1.jpg
  public/images/maintainedData/techDemo/group2_2.jpg
  public/images/maintainedData/techDemo/group3.jpg
Labels: bug, refactor

#131 feat(custom-drawer): add developed by us text
  components/custom_drawer/custom_drawer.tsx
Labels: feature

#139 refactor(styling): fix styling across app
  clients/challenge/challenge_client.tsx
  clients/pi_community/pi_community_client.tsx
  components/carousel_tab/carousel_tab.tsx
  components/info_card/info_card.tsx
  utils/font_utils.ts
Labels: refactor

#141 feat(next-config): add static build config
  components/button_card/button_card.tsx
  components/custom_drawer/custom_drawer.tsx
  components/info_card/info_card.tsx
  next.config.mjs
Labels: enhancement, feature
